// <auto-generated />
namespace ShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applydataannotations5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applydataannotations5));
        
        string IMigrationMetadata.Id
        {
            get { return "201901160901340_applydataannotations5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
