// <auto-generated />
namespace ShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applydataannotations13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applydataannotations13));
        
        string IMigrationMetadata.Id
        {
            get { return "201902010423431_applydataannotations13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
