// <auto-generated />
namespace ShoppingCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class applydataannotations15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applydataannotations15));
        
        string IMigrationMetadata.Id
        {
            get { return "201902040710301_applydataannotations15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
